### ISSUE TITLE
Contact Errors -

### ISSUE THREAD

**Issue by kjhill1** [ChibiMuse/IT163_DevTeam2#15]
Line 2 Stray HTML tag removed
Line 119, 127 alt attr tags added to img

line 118 removed stray DIV tag (double check maybe buried) 

Error Report on line 119 as nav tag is stray but see an open tag on line 93 NOT Removing JIC

**Comment by ChibiMuse** [comment]
html tag removed.
ty for alt tag catch!
div tag was buried, so left it in.
